name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: bash 
      run: echo $PWD
    - name: Checkout
      uses: actions/checkout@master
    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile
